#!/bin/bash
total 40
drwxr-xr-x 2 root root 198 Jul 10 13:47 .
drwxr-xr-x 6 root root 153 Jul 10 11:27 ..
-rwxr--r-- 1 root root  32 Jul 10 11:59 0-hello_world
-rwxr--r-- 1 root root  28 Jul 10 12:23 1-confused_smiley
-rwxr--r-- 1 root root  28 Jul 10 12:48 2-hellofile
-rwxr--r-- 1 root root  39 Jul 10 12:53 3-twofiles
-rwxr--r-- 1 root root  35 Jul 10 12:58 4-lastlines
-rwxr--r-- 1 root root  35 Jul 10 13:00 5-firstlines
-rwxr--r-- 1 root root  40 Jul 10 13:13 6-third_line
-rwxr--r-- 1 root root  99 Jul 10 13:35 7-file
-rwxr--r-- 1 root root  43 Jul 10 13:47 8-cwd_state
-rw-r--r-- 1 root root  42 Jul 10 11:58 README.md
